version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:3000'
    env_file:
      - .env
    environment:
      - PORT=3000
      - RABBITMQ_CONNECTION=amqp://user:password@rabbitmq
      - REDIS_CONNECTION=redis://redis:6379
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 3s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 3s
      timeout: 10s
      retries: 5

#  nginx:
#    build: ./nginx
#    ports:
#      - '8080:8080'
#    networks:
#      - appnetwork
#    depends_on:
#      - app

#networks:
#  appnetwork: